[project]
name = "neca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ninja==1.11.1",
    "numpy==1.24.4",
    "pyyaml==6.0",
    "torch==1.9.0",
]
